# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 740b890c925f278f21f15333ddaec8684a4c0c8478538ec20d19d45bf30a8d9824b07d2f5672812b1d0529fa2a9d98ef19baa636e3165795c21c33f319070b46

test:
  secret_key_base: 4f453cde12a3ed05b35a859079ee0ba9e5d5613119e04edf26c526a167e41d5c4eabdad0a514b002225f199d74027ce12f84c74404baf98669b83230d59f9a70

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
